feat/97 implement post like service
Breaking-Dope/breaking-backend pull request #101
Opened 2022-07-18 14:45 UTC by MinwuTheQuant

## 관련 이슈

close #97 

## 예상 리뷰 시간
10-min

## 추가 또는 변경사항

- 제보의 좋아요 기능을 구현했습니다
- 제보의 좋아요 취소 기능을 구현했습니다.
- 제보를 좋아요 한 유저의 리스트를 리턴하는 기능을 구현했습니다.
- 각 기능에 해당하는 테스트 케이스를 작성했습니다.

## 스크린샷

-PostLike에 단방향 매핑으로 처리했습니다.
-OnDelete(action = OnDeleteAction.CASCADE)를 추가하여, 단방향임에도 Cascade.DELETE가 구현되도록 처리했습니다. (테스트 케이스 까지 따로 만들어 처리했습니다.)

<img width="500" alt="스크린샷 2022-07-18 오후 11 41 06" src="https://user-images.githubusercontent.com/87322089/179536629-ec2d7e38-6568-46f4-b74f-146d8f49aec6.png">

## 기타

- 좋아요나 팔로우 등 기능은 모두 단방향 매핑으로 가져가는 것이 훨씬 깔끔한 것 같습니다. 이에 맞춰 종전에 구현한 유저 팔로우도 단방향 매핑으로 리펙토링 할 계획입니다.

2022-07-18 15:09 UTC, JinuCheon requested changes
코맨트 확인 바랍니다~

2022-07-18 15:09 UTC, JinuCheon commented on src/main/java/com/dope/breaking/api/PostLikeAPI.java
> +    @PostMapping("/post/like/{postId}")
엇. 이거 /post/:postid/like 로 하는게 좋다네요.

연관있는 것의 뒤에 queryparam이 온답니다.

2022-07-18 15:09 UTC, JinuCheon commented on src/main/java/com/dope/breaking/api/PostLikeAPI.java
> +    @PostMapping("/post/like/{postId}")
밑에 애들이랑 notion api sheet도 수정 고고!

2022-07-18 15:09 UTC, JinuCheon commented on src/main/java/com/dope/breaking/exception/ErrorCode.java
> +    ALREADY_UNLIKED("BSE421","이미 좋아요를 선택하지 않았습니다."),
에러코드 생성은 PM한테 요청하세요.

오전에 코드 다시 만들어 줄테니, 다시 작성 부탁드립니다.

2022-07-18 15:09 UTC, JinuCheon commented on src/main/java/com/dope/breaking/exception/ErrorCode.java
> +    ALREADY_UNLIKED("BSE421","이미 좋아요를 선택하지 않았습니다."),
그리고 코드도 잘못 작성되어있음.
노션에도..

2022-07-19 02:23 UTC, Martin0o0 approved these changes
수고하셨습니다.! PM님이 말씀해주신 부분은 수정 부탁드리겠습니당!~

2022-07-19 02:23 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/exception/ErrorCode.java
> +    ALREADY_UNLIKED("BSE421","이미 좋아요를 선택하지 않았습니다."),
요부분 중복인거 같아요!

2022-07-19 02:23 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/domain/post/PostLike.java
> +    @ManyToOne(fetch = FetchType.LAZY)
OnDelete 어노테이션을 처음접해봅니다! 덕분에 찾아보면서 공부가 되었네요! 좋은 정보 알아갑니다!~

2022-07-19 02:35 UTC, JinuCheon requested changes
BSE420 : 이미 팔로우 중인 유저입니다.
BSE421 : 이미 언팔로우 중인 유저입니다.
BSE458 : 이미 좋아요를 선택했습니다.
BSE459 : 이미 좋아요를 선택하지 않았습니다.

뭔가 좋아요를 선택? 했습니다 라고 하니까 이상하긴 한데,
다른 문장이 떠오르지 않음..
혹시 더 좋은 문장이 있으면, 수정 요청 부탁.

그리고 에러코드는 제가 관리해서, 생성 요청을 해주세요.
노션은 읽기 전용으로 수정하겠습니다.

2022-07-19 03:45 UTC, JinuCheon approved these changes

2022-07-19 03:52 UTC, merged