feat: add hashtag features for comments
Breaking-Dope/breaking-backend pull request #147
Opened 2022-07-27 06:50 UTC by MinwuTheQuant

## 관련 이슈

close #131 

## 예상 리뷰 시간
30-min

## 추가 또는 변경사항

- 해시태그 관련 대대적인 리펙토링을 완료했습니다:
  - Hashtag 엔티티를 삭제하고, PostCommentHashtag의 이름을 Hashtag로 변경했습니다. 이로써 해시태그와 제보/댓글은 다대일 관계를 가지게 됩니다.
  - @Martin0o0 마틴님이 만들어 놓으신 savePostHashtag와 modifyPostHashtag 역시 saveHashtag와 updateHashtag로 통합했습니다. 이를 통해 제보와 댓글의 해시태그 모두 하나의 메서드로 활용가능합니다.
  - @Martin0o0 님이 만들어 놓으신 해시태그 삭제 관련문제도 리펙토링을 완료했습니다. 이제 삭제 후 따로 매핑테이블에 가서 검증하는 절차가 필요없어졌습니다. 그래서 OnDelete를 설정하여 해당 제보/댓글이 삭제 되었을 때 해시태그 객체도 자동 삭제 되게 설정했습니다.

- 클라이언트 쪽에서의 댓글 작성 및 수정요청을 받기 위한 CommentRequestDto를 만들었습니다. 이 dto에는 아래와 같이 두가지 필드가 있습니다:
  1. 댓글 내용 (String)  (null 불가)
  2. 해시태그 내용 (List<String>) (null 가능)

- 바뀐 기능에 맞춰 테스트코드를 전면적으로 수정하고 추가했습니다.

## 스크린샷

## 기타

- @Martin0o0 리펙토링 완료 후 post관련 테스트코드가 문제 없이 돌아가는 것을 확인했습니다. 하지만 제가 놓친 부분이 있을 수도 있으니 merge후 재확인 부탁드립니다.

2022-07-27 11:54 UTC, JinuCheon commented on src/test/java/com/dope/breaking/service/CommentServiceTest.java
> +    @DisplayName("댓글을 삭제할 경우, 해당하는 PostCommentHashtag 객체도 삭제된다.")
테스트 설명 수정 부탁!

2022-07-27 11:54 UTC, JinuCheon commented on src/test/java/com/dope/breaking/service/CommentServiceTest.java
> +    @DisplayName("댓글에 해시태그가 존재할 경우, 해시태그가 정상적으로 작동된다")
정상적으로 등록된다.

2022-07-27 11:56 UTC, JinuCheon approved these changes
고생하셨습니다~~

테스트 네이밍만 수정해주세요~~
AommentAPI 부분에 dto를 service 계층으로 통째로 넘기는게 좋을 것 같습니다.

2022-07-28 09:46 UTC, Martin0o0 requested changes
수고하셨습니다.!

2022-07-28 09:47 UTC, Martin0o0 approved these changes
수고하셨습니다.

2022-07-28 11:34 UTC, merged