feat: implement bookmark function
Breaking-Dope/breaking-backend pull request #154
Opened 2022-07-28 11:06 UTC by Martin0o0

## 관련 이슈

close #133 

## 예상 리뷰 시간
10-min

## 추가 또는 변경사항

1. 북마크 기능을 구현하였습니다. 좋아요 기능과 유사하여 기능 및 로직 설계는 좋아요 기능과 동일하겠습니다.

## 스크린샷

없음.
## 기타

현재, 개인적인 사정으로 인하여 늦게 PR 날리게 된 점 진심으로 죄송하다는 말씀 드리고 싶습니다. 한동안 개인사로 인해 참여가 저조할 것으로 생각합니다. 진심으로 사죄드립니다.

2022-07-28 12:38 UTC, MinwuTheQuant approved these changes
수고하셨습니다~

2022-07-29 02:28 UTC, JinuCheon requested changes
북마크 생성과 삭제가 로직이 똑같은데, 한 번 확인해주세요.

2022-07-29 02:28 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/BookmarkService.java
> +    }
bookmark와 로직이 같은데, 한 번 확인해주세요.

2022-07-29 03:25 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/BookmarkService.java
> +    }
허걱! 잘못 작성되었네요ㅜ 다음부터 조심하겠습니다.

2022-07-29 03:35 UTC, JinuCheon approved these changes
서비스 테스트코드 작성이 필요한 것 같습니다.

- 북마크 되었는지 조회해서 확인
- 북마크 해제되었는지 조회해서 확인

천천히 해주세요 ~

2022-07-29 07:39 UTC, merged