feat: add transaction list method
Breaking-Dope/breaking-backend pull request #167
Opened 2022-08-02 10:41 UTC by MinwuTheQuant

## 관련 이슈

close #162 

## 예상 리뷰 시간
15-min

## 추가 또는 변경사항

- 유저의 입출금 및 제보 구매/판매 내역을 최신순으로 리턴하는 기능을 구현했습니다.
   - dto에 transactionTime에 추가했습니다.
   - dto에 balance를 추가했습니다. (매번 금액이 더 해지고 깎인 후 잔액을 추가했습니다)
   - 위와 같은 설계는 토스의 입출금내역을 참고했습니다.
- 이에 맞는 테스트코드를 작성했습니다. 

## 스크린샷

<img width="960" alt="스크린샷 2022-08-02 오후 4 58 20" src="https://user-images.githubusercontent.com/87322089/182355684-8aa56373-a5ae-4e5f-b394-65b1e11a638d.png">

## 기타

- 제보 구매자 리스트를 구현하겠습니다.
- 대대적인 API 시트 정리에 들어가겠습니다.

2022-08-02 14:05 UTC, JinuCheon requested changes
DB 관련 작업 시, spring data jpa 에서 제공하는 기능을 최대한 활용해주세요.

2022-08-02 14:05 UTC, JinuCheon commented on src/main/java/com/dope/breaking/domain/financial/Transaction.java
> +public class Transaction extends BaseTimeEntity {
BaseTimeEntity 는 왜 들어가는 건가요?

2022-08-02 14:05 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/TransactionService.java
> +        }
spring data jpa 쿼리 자체에서 지원하는 order by 를 사용해서 정렬해주세요. 

그렇게 되면 따로 이렇게 필드 하나하나 add 하는 과정도 필요없을듯.

2022-08-03 02:26 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/domain/financial/Transaction.java
> +public class Transaction extends BaseTimeEntity {
거래가 일어난 날짜를 기록해야 합니다. 몇월 몇일에 거래가 일어났다고 알려줘야하거든요. 밑에 createdTime을 쓰려면 baseTimeEntity를 붙여야합니다.

2022-08-03 02:28 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/TransactionService.java
> +        }
잘 이해를 못했습니다. 여기서 add 한 건 자체 데이터가 아닌 dto를 생성하고 리스트에 넣는 것입니다. 어떤 식의 orderBy를 넣으라는 것인지 설명해주시면 감사하겠습니다.

2022-08-03 06:04 UTC, Martin0o0 approved these changes
수고하셨습니다!

2022-08-03 06:04 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/TransactionService.java
> +        }
stack구조의 리스트다 보니  된 최신의 거래 내역이 마지막 인덱스에 담기는 것을, reverse를 통해 최신 내역이 첫번째 인덱스에 오도록 한 뒤, 하나씩 dto화 해서 리스트해주는 방식으로 보입니다. 아마 진우님은 reverse를 통해 리스트를 뒤집지 말고, orderbyCreatedTime으로 디비에서 자체적으로 정렬을 가진 뒤 그냥 dto화 된 리스트를 반환하다록 요구하는 것 같습니다.

2022-08-03 06:04 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/TransactionService.java
> +        }
추가적으로 forEach문을 통해 일일히 add 해주는 것보다 Stream Api로 .map().collect()를 사용해 보시는것 추천드립니다! 코드도 간결될 뿐더러 가독성이 높아지더라구요! stream api한번 찾아보시는것 추천드립니다.

2022-08-04 05:31 UTC, JinuCheon approved these changes
굿!
고생하셨습니다 :)

2022-08-04 05:31 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/TransactionService.java
> +        }
으흠 제가 조금 잘못 생각한 부분이 있어서 다시..

1. 정렬은 DB에서 하면 된다.
지금 코드를 보면, collection.reverse 를 사용해서 역순으로 정렬했네요.
sql에서 기본적으로 제공하는 정렬기능 (order by ~ desc) 옵션이 있는데,
spring data jpa에서도 이거를 사용 가능.
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation

2. DTO에 Entity 값을 매핑해서 넣어주는거는, DTO 내부에 method를 만드는게 좋아보임
불필요한 로직을 최대한 감춰서 큰 흐름(서비스계층)을 간결하게 가져가는게 좋을듯

2022-08-04 05:31 UTC, JinuCheon commented on src/main/java/com/dope/breaking/domain/financial/Transaction.java
> +public class Transaction extends BaseTimeEntity {
아 자동 생성이 안되는군요 굳

2022-08-04 05:55 UTC, merged