Feat: MediaService implementation & Corresponding test cases
Breaking-Dope/breaking-backend pull request #21
Opened 2022-06-30 13:01 UTC by MinwuTheQuant

## 관련 이슈

close #17

## 예상 리뷰 시간
20 min

## 추가 또는 변경사항
- MediaService를 추가했습니다.
- MediaService에 uploadMedias 메서드를 추가했습니다. 구체적 기능은 아래와 같습니다:
   -  클라이언트로부터 이미지를 List<Multiparts> 형식으로 매핑합니다.
   - UUID로 새 파일 이름을 생성하고, 원래의 extension을 조합하여 새로운 파일이름을 생성합니다.
   - 지정 된 디렉토리로 파일을 저장합니다. (디렉토리는 추후에 AWS상으로 변경합니다. 스크린샷 참고 바랍니다)
   - List<String>형식으로 모든 파일이름을 리턴합니다. 
- MediaService에 findMediaType 메서드를 추가했습니다. 구체적 기능은 아래와 같습니다:
  - 파일 이름에서 extension을 뽑아옵니다.
  - ("mp4","mov","mpg","mpeg","gif","rm","vob") 중 해당 될 경우, 미디어타입은 영상으로 지정됩니다.  
  _- 추후에 추가할 익스텐션은 논의해봐도 좋을 것 같습니다._
- MediaService에 createMediaEntities 메서드를 추가했습니다. 구체적 기능은 아래와 같습니다:
  - 파라미터로 uploadMedias 메서드로 리턴 받은 List<String>과, 해당하는 post를 받습니다.
  - findMediaType로 MediaType을 확인합니다.
  - builder를 통해 Media 엔티티를 생성하고 db에 저장합니다.
- findMediaType과 createMediaEntities의 테스트케이스를 생성했습니다. 

## 스크린샷

- 아래와 같이 임시적으로 제 로컬에 이미지를 저장할 디렉토리를 지정했습니다. 추후에 변경하면 될 것 같습니다. 
<img width="669" alt="스크린샷 2022-06-30 오후 9 52 58" src="https://user-images.githubusercontent.com/87322089/176681931-afce7ecb-f84c-4f06-8905-1cbb47704a85.png">

- createMediaEntities를 테스트한 결과 문제 없이 실행되는 것을 확인 할 수 있었습니다. 
<img width="467" alt="스크린샷 2022-06-30 오후 9 56 22" src="https://user-images.githubusercontent.com/87322089/176682599-15879cfd-37f5-47fd-b11f-120c7bdf7556.png">
## 기타

- UUID에 대해 알게 되었습니다.
- Service와 Repository의 분리에 대해서 한 층 더 이해할 수 있었습니다. 앞으로 양 쪽의 역할 분담이 확실하게 만들도록 주의해야겠습니다.

2022-06-30 13:34 UTC, Martin0o0 approved these changes
수고많이 하셨습니다!

2022-06-30 13:34 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/MediaService.java
> +                String generatedFileName = UUID.randomUUID().toString()+"."+extension;
혹시 모를 중복 파일명을 대비하여 랜덤 해쉬값을 부여하는 방식이 매우 좋다고 생각합니다! 좋은 방식인거 같습니다~!

2022-06-30 13:34 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/MediaService.java
> +    private String dirName = "/Users/gimmin-u/Desktop/testImgFolder";
디렉토리명을 final로 선언하여 상수로 취하는 것은 어떨까요? 
AWS로 디렉토리 변경때 상수취급하는것이 좋다고 생각합니다!

2022-06-30 13:34 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/MediaService.java
> +        List<String> videoExtension = Arrays.asList("mp4","mov","mpg","mpeg","gif","rm","vob");
파일 형식을 리스트로 취합 후, 판별하는 방식 좋네요!

2022-06-30 15:25 UTC, JinuCheon requested changes
api test file 지워줘요!!

2022-06-30 15:25 UTC, JinuCheon commented on src/main/java/com/dope/breaking/apiTests/MediaUploaderTest.java
> +package com.dope.breaking.apiTests;
테스트....파일....지워...줘.....요.....

2022-06-30 15:25 UTC, JinuCheon commented on src/main/java/com/dope/breaking/domain/media/Media.java
> +    }
오.. 빌더 적용 방법 배워갑니다.

2022-06-30 15:25 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/MediaService.java
> +    private String dirName = "/Users/gimmin-u/Desktop/testImgFolder";
굳

2022-07-01 01:46 UTC, JinuCheon approved these changes

2022-07-01 01:47 UTC, merged