feat : add thumbnail image creation function
Breaking-Dope/breaking-backend pull request #36
Opened 2022-07-05 11:26 UTC by Martin0o0

## 관련 이슈

close #31 

## 예상 리뷰 시간
20-min

## 추가 또는 변경사항
1. 유저가 지정한 사진 혹은 동영상(인덱스)에 썸네일 사진을 생성하는 기능을 추가하였습니다.
 기존 MediaService단에서 썸네일만 생성하는 메서드를 만들려고 하였으나, 톰캣 내부의 알 수 없는 오류로 인하여 인덱스와 파일을 같이 받아 생성하는 쪽으로 방향을 바꾸었습니다. 

2. 파일 최대 용량을 임시로 100MB까지 올렸습니다.
  대다수의 영상이 50MB를 넘기에 임시로 올렸습니다.

3. Thumbnailor 라이브러리와 Jcodec 라이브러리의 dependency를 축가하였습니다.
  두 라이브러리를 통해 사진 및 동영상의 썸네일 생성을 구현하였습니다.

4. 썸네일은 최대 너비 500, 높이 500으로 맞추었습니다. 
  height와 width가 동일하면 사진이 왜곡되기에, 최대 크기에 맞게 다운스케일링 하도록 구현하였습니다.

5. Optional<Principal> 구문을 삭제하여습니다. null Exception을 잡으려 Opional을 사용하였지만, 되려 에러가 발생하는 문제가 생겨 if(principal == null)로 대체하였습니다. 

## 스크린샷
<img width="722" alt="스크린샷 2022-07-05 오후 4 40 21" src="https://user-images.githubusercontent.com/62254434/177316851-0880fa2d-0043-401a-8418-3299f2b0c36b.png">
<img width="1582" alt="스크린샷 2022-07-05 오후 4 43 32" src="https://user-images.githubusercontent.com/62254434/177316920-3019abad-ea4c-421d-bdb4-31e0026ddb62.png">
<img width="1102" alt="스크린샷 2022-07-05 오후 8 09 28" src="https://user-images.githubusercontent.com/62254434/177316990-b970fbab-b97e-4a9a-91d3-c73b55ecf92d.png">
![s_49e69562-bc31-43d7-9e1b-2e3fe54eb4d1](https://user-images.githubusercontent.com/62254434/177317140-8cb0d1fa-b2cb-41b8-a294-c503cba0f928.JPG)

## 기타
현재 동영상 썸네일 제작하는 부분에서 시간이 너무 지체되어서, 나중으로 미루고 수정단계 돌입하도록 하겠습니다. 우선, 가로 영상의 경우세로로 썸네일이 생성됩니다. 추후 수정하도록 하겠습니다. 불필요한 로그를 삭제하였습니다. 또한, 파일 저장 시 영상은 mp4로 저장하도록 수정하였습니다.

2022-07-05 13:40 UTC, JinuCheon requested changes
요청한 Post entity 수정 부탁해요 ~

2022-07-05 13:40 UTC, JinuCheon commented on src/main/java/com/dope/breaking/domain/post/Post.java
> +    private String thumbnailURL;
thumbnailImgURL 로 수정해주세요~~~

2022-07-05 13:40 UTC, JinuCheon commented on src/main/java/com/dope/breaking/domain/post/Post.java
> +
+ viewCount 추가 부탁드립니다!

2022-07-05 15:33 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/api/PostAPI.java
> +        if (principal ==  null) {
오 이런 식으로 변경이 되었군요. 제가 지금 올린 PR에서는 변경 전의 코드를 복붙했는데, 이런 식으로 똑같이 수정하겠습니다.

2022-07-05 15:47 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/MediaService.java
> +
썸네일을 위한 폴더를 따로 만드신 이유는 메인페이지 띄울 때 효율을 위함인가요?

2022-07-05 15:50 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/MediaService.java
> +                        Thumbnailator.createThumbnail(destination, thumdestination, 500, 500);
오.. 이런게 있군요..

2022-07-05 15:51 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/MediaService.java
> +
영상에서 썸네일 따오는 법 배우고 갑니다!

2022-07-05 15:51 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/MediaService.java
> +                        mediaList.put("thumbnail", Arrays.asList(generatedThumFileName));
주석은 추후 사용할 것 아니면 지우는 게 좋을 것 같네요!

2022-07-05 16:18 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/MediaService.java
> +            return mediaList;
mediaList를 return 하시는 이유가 궁금합니다!
지금까지 보았을 때는 이 mediaList가 왜 쓰이는지 잘 모르겠습니다.

2022-07-05 16:20 UTC, MinwuTheQuant reviewed
고생많으셨습니다! 
내일 아침 제가 코멘트 달아드린 부분 같이 얘기해보고 Approve 하는식으로 하면 좋을 것 같습니다.
그리고 이 참에 json 말고 string 처리하는 부분까지 같이 덧붙이면 좋을 것 같네요!

2022-07-06 01:07 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/MediaService.java
> +
같은 폴더에 두게되었을때, 나중에 사진 위치를 찾기 힘들어 질 것 같아 일부로 빼두었습니다

2022-07-06 11:49 UTC, MinwuTheQuant approved these changes
수고하셨습니다!

2022-07-06 11:49 UTC, JinuCheon approved these changes
고생하셨수!

2022-07-06 11:51 UTC, merged