feat: implement follower/following list
Breaking-Dope/breaking-backend pull request #58
Opened 2022-07-09 12:02 UTC by MinwuTheQuant

## 관련 이슈

close #53 

## 예상 리뷰 시간
5-min

## 추가 또는 변경사항

- 팔로워 및 팔로잉 리스트를 리턴하는 메서드를 followService 계층에 추가했습니다.
- 로그인 하지 않은 유저도 접근하는 기능이기 때문에 Preauthorize 는 제거 하였습니다.

## 스크린샷

아래와 같이 잘 작동하는 모습입니다:

<img width="483" alt="스크린샷 2022-07-08 오후 12 26 14" src="https://user-images.githubusercontent.com/87322089/178104722-5d07da29-9268-43a9-8d4c-817864dcb3cc.png">

## 기타

- 컨트롤러 단에 코드를 최소화 하고, 모든 기능을 서비스 계층에 넣도록 주의하며 구현했습니다. 앞으로도 신경쓰며 코드를 짜야할 것 같네요.
- 주말인데 좀 쉬시고 천천히 리뷰 해주세요 ^^

2022-07-09 12:11 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/FollowService.java
> +
불필요한 스페이스 제거!

2022-07-09 12:12 UTC, JinuCheon requested changes
테스트코드 부탁드립니다.

이전에 작성했던 팔로우 기능 테스트를 먼저 작성해주시고,
해당 팔로우 기능을 이용해서 dummy 를 추가 후,
이번에 작성한 리스트 불러오는 테스트를 작성해주세요!

2022-07-11 04:21 UTC, Martin0o0 approved these changes
수고하셨습니다!

2022-07-11 04:21 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/FollowService.java
> +
예외처리 방식 깔끔하네요! 참고하겠습니다~!

2022-07-15 01:43 UTC, Martin0o0 approved these changes
전에것도 포함되어있어서 그런지 코드 다시보게 되서 감회가 새롭네요~! 수고 정말 많이 하셨습니다!

2022-07-15 01:43 UTC, Martin0o0 commented on src/main/java/com/dope/breaking/service/MediaService.java
파일 예외처리를 이렇게 하셨군요! 참고하겠습니다.

2022-07-15 02:15 UTC, JinuCheon commented on src/main/java/com/dope/breaking/api/RelationshipAPI.java
> +    @GetMapping("follow/following/{userId}")
/ 누락! 밑에도!

2022-07-15 02:37 UTC, JinuCheon requested changes
확인 한 번 부탁드려요.

2022-07-15 02:37 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/FollowService.java
> +        userService.save(followedUser);
이거 저는 개인적으로 userRepository에 직접 접근해서 save 써야한다고 생각하는데 어떻게 생각하시나요.
이 코드는, someRepository에 접근하기 위해서, 반드시 someService를 통해서 접근하는 형태..?

개인적으로 서비스에서 서비스를 의존하면, 사실 두 개의 클래스에 의존하는 형태라고 생각..
차라리 바로 userRepository에 접근하는게 어떨까하는 생각입니다.

@Martin0o0

2022-07-15 02:37 UTC, JinuCheon commented on src/main/java/com/dope/breaking/api/RelationshipAPI.java
> +        return ResponseEntity.ok().body(followInfoResponseDtoList);
변수에 담지 않고, 바로 return 해줘도 될 듯.

2022-07-15 02:37 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/FollowService.java
> +        AFollowB(followingUser,followedUser);
사실 이 AFollowB 라는 매서드 네이밍이 좋을지는 잘 모르겠어요.
follow만 해도 의도가 명확하다고 생각되는데,

어떤 관계가 있다고 A@@B 관계를 매서드명에서 표현하면, 다른 매서드들도 이렇게 표현해야 할 것들이 많을텐데 지저분해지지 않을까 생각됩니다.

일반적인 네이밍 방법은 아닌듯!

2022-07-15 02:37 UTC, JinuCheon commented on src/main/java/com/dope/breaking/service/FollowService.java
> +            followInfoResponseDtoList.add (new FollowInfoResponseDto(followedUser.getId(),followedUser.getNickname(),followedUser.getStatusMsg(),followedUser.getProfileImgURL()));
매서드 뒤에 공백좀 지워주세요 !

- 이 코드 전체 확인 부탁드립니다.
- 공백 넣어야 할 곳은 넣어주시고, 불필요한 곳을 빼주세요.

2022-07-15 02:37 UTC, JinuCheon commented on src/main/java/com/dope/breaking/api/RelationshipAPI.java
> +    public ResponseEntity<?> followerUsers (@PathVariable Long userId){
타입 생략을 자제해주세요!
진짜 어쩔 수 없는 상황에서만..

2022-07-15 02:45 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/api/RelationshipAPI.java
> +        return ResponseEntity.ok().body(followInfoResponseDtoList);
수정했습니다!

2022-07-15 02:47 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/FollowService.java
> +            followInfoResponseDtoList.add (new FollowInfoResponseDto(followedUser.getId(),followedUser.getNickname(),followedUser.getStatusMsg(),followedUser.getProfileImgURL()));
넵 수정했습니다!

2022-07-15 02:47 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/api/RelationshipAPI.java
> +    public ResponseEntity<?> followerUsers (@PathVariable Long userId){
수정했습니다~

2022-07-15 03:05 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/FollowService.java
> +        AFollowB(followingUser,followedUser);
follow/unfollow로 바꿨습니다!

2022-07-15 03:27 UTC, MinwuTheQuant commented on src/main/java/com/dope/breaking/service/FollowService.java
> +        userService.save(followedUser);
싹 다 갈아엎었습니다. 확인 부탁드려요!

2022-07-15 03:35 UTC, JinuCheon approved these changes
LGTM

2022-07-15 03:36 UTC, merged